### PR TITLE
Update Saft Page

### PR DESCRIPTION
**Pull request by Techthy**
- remove old dates
- add new dates
- make picture and text generic

### CODE REVIEW

**Comment by Huhn300** [comment]
The code looks good. The page does not look optimal in the mobile version. The space between the images and the SAFT text is too large. I would remove the bottom image in the mobile version.
IMG_C3FCEA9B13C4-1

**Comment by Huhn300** [comment]
The code looks good. The page does not look optimal in the mobile version. The space between the images and the SAFT text is too large. I would remove the bottom image in the mobile version.
I have tried to fix this in the latest commit.
IMG_C3FCEA9B13C4-1

**Review by Huhn300 — COMMENTED** [review]
Code looks good. I have optimized the style in the mobile version. Please check again.

**Comment by Techthy** [comment]
@Huhn300 yes you are right. Thanks for fixing. I further improved the breakpoint to have the image below the text until it is displayed next to it. (Changed md to lg which is the breakpoint for the two column layout)
Please look over it briefly and if you're satisfied consider approving ;)

**Comment by Huhn300** [comment]
> @Huhn300 yes you are right. Thanks for fixing. I further improved the breakpoint to have the image below the text until it is displayed next to it. (Changed md to lg which is the breakpoint for the two column layout) Please look over it briefly and if you're satisfied consider approving ;)

 Thank you for the answer and the explanations regarding md and ld.

**Review by Huhn300 — APPROVED** [review]
LGTM

**Pull request merged**
