### PR TITLE
Add calendar to page

### PR DESCRIPTION
**Pull request by Techthy**
- added basic functionality to pocketbase
- added list overview and individual pages with smart loading (no refetching if event is already there)
Warning: adding events only possible through backend. Time differences must be kept in mind. (Pocketbase operates on  UTC and we're UTC + 2)

See the issue for next to dos

### CODE REVIEW

**Review by Huhn300 — COMMENTED** [review]
The code looks good to me so far and I could not find any errors. However, if no image is uploaded to a Event, for example, the view no longer looks nice.

**Comment by Huhn300** [comment]
I'm still missing some functions that I would like to see in the calendar:
Link to an ical subscription
automatic weekly/repeating events can be displayed
The time in Pocketbase is UTZ, which is not practicable when entering because it is converted on the website.

**Review by Zocker1999NET — CHANGES_REQUESTED** [review]
The code looks fine for me as well, but the latest version uploaded here (eb52745d3c4f93201032f7fff578e9520db56b6a) failed to build on my systems.

The last lines of the log are:
```
ClientResponseError 404: The requested resource wasn't found.
    at new ClientResponseError (file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2306)
    at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:47300
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async load (file:///app/.svelte-kit/output/server/entries/pages/events/kalender/_page.ts.js:7:21)
    at async load_data (file:///app/.svelte-kit/output/server/index.js:540:18)
    at async file:///app/.svelte-kit/output/server/index.js:1961:18 {
  url: 'https://api.smd-karlsruhe.de/api/collections/calendar/records?page=1&perPage=200&sort=%2Bstart_date_time&filter=start_date_time%20%3E%3D%20%222024-08-22T21%3A56%3A47.503Z%22',
  status: 404,
  response: {
    code: 404,
    message: "The requested resource wasn't found.",
    data: {}
  },
  isAbort: false,
  originalError: {
    url: 'https://api.smd-karlsruhe.de/api/collections/calendar/records?page=1&perPage=200&sort=%2Bstart_date_time&filter=start_date_time%20%3E%3D%20%222024-08-22T21%3A56%3A47.503Z%22',
    status: 404,
    data: {
      code: 404,
      message: "The requested resource wasn't found.",
      data: {}
    }
  }
}
  303 /intern -> /account/login?redirect=/intern

node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /events/kalender/[slug]

See https://kit.svelte.dev/docs/page-options#prerender-troubleshooting for info on how to solve this
    at prerender (file:///app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:505:9)
    at async MessagePort.<anonymous> (file:///app/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)

Node.js v20.17.0
Error: building at STEP "RUN npm run build": while running runtime: exit status 1
```

**Comment by Techthy** [comment]
> The code looks fine for me as well, but the latest version uploaded here ([eb52745](https://github.com/smd-ka/smd-ka/commit/eb52745d3c4f93201032f7fff578e9520db56b6a)) failed to build on my systems (for reference: I’m using podman, not “official” docker; but the error message seems to indicate a different issue).
> 
> The last lines of the log are:
> 
> ```
> ClientResponseError 404: The requested resource wasn't found.
>     at new ClientResponseError (file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2306)
>     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:47300
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async load (file:///app/.svelte-kit/output/server/entries/pages/events/kalender/_page.ts.js:7:21)
>     at async load_data (file:///app/.svelte-kit/output/server/index.js:540:18)
>     at async file:///app/.svelte-kit/output/server/index.js:1961:18 {
>   url: 'https://api.smd-karlsruhe.de/api/collections/calendar/records?page=1&perPage=200&sort=%2Bstart_date_time&filter=start_date_time%20%3E%3D%20%222024-08-22T21%3A56%3A47.503Z%22',
>   status: 404,
>   response: {
>     code: 404,
>     message: "The requested resource wasn't found.",
>     data: {}
>   },
>   isAbort: false,
>   originalError: {
>     url: 'https://api.smd-karlsruhe.de/api/collections/calendar/records?page=1&perPage=200&sort=%2Bstart_date_time&filter=start_date_time%20%3E%3D%20%222024-08-22T21%3A56%3A47.503Z%22',
>     status: 404,
>     data: {
>       code: 404,
>       message: "The requested resource wasn't found.",
>       data: {}
>     }
>   }
> }
>   303 /intern -> /account/login?redirect=/intern
> 
> node:internal/event_target:1094
>   process.nextTick(() => { throw err; });
>                            ^
> Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
>   - /events/kalender/[slug]
> 
> See https://kit.svelte.dev/docs/page-options#prerender-troubleshooting for info on how to solve this
>     at prerender (file:///app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:505:9)
>     at async MessagePort.<anonymous> (file:///app/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
> Emitted 'error' event on Worker instance at:
>     at [kOnErrorMessage] (node:internal/worker:326:10)
>     at [kOnMessage] (node:internal/worker:337:37)
>     at MessagePort.<anonymous> (node:internal/worker:232:57)
>     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
>     at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
> 
> Node.js v20.17.0
> Error: building at STEP "RUN npm run build": while running runtime: exit status 1
> ```
> 
> Question in that context, because I’m unsure about that: Is the error message correct about that the calendar pages are currently pre-rendered? Generally I’m a fan of pre-rendering, but in case of a calendar which gets updated regularly, I think having dynamic updates would be better.

Hmm this is very interesting but same here. Removing the ssr fixes the problem. I would be super interesting to know why this is failing. Maybe it has something to do that I fetch the data inside a subscription to a store?

**Comment by Techthy** [comment]
> I'm still missing some functions that I would like to see in the calendar: Link to an ical subscription automatic weekly/repeating events can be displayed The time in Pocketbase is UTZ, which is not practicable when entering because it is converted on the website.

Please have a look at the issue. These things are known by me but making too large of a PR is tedious to review. I will create an option to create Events today. The ical subscription is on the to do list but is just not the MVP (Most valuable product) right now.

**Review by Huhn300 — APPROVED** [review]
LGTM

**Pull request merged**
